apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@github.com/arkinfotech24/eks-gitops
  ref:
    branch: master
  secretRef:
    name: flux-system

