apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: eks-gitops
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/arkinfotech24/eks-gitops
  ref:
    branch: master

